// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

/**
 * <pre>
 * Gossip message containing multiple user updates
 * </pre>
 *
 * Protobuf type {@code gossip.GossipMessage}
 */
public final class GossipMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gossip.GossipMessage)
    GossipMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      GossipMessage.class.getName());
  }
  // Use GossipMessage.newBuilder() to construct.
  private GossipMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GossipMessage() {
    messageId_ = "";
    sourceNodeId_ = "";
    users_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_GossipMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_GossipMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.gmathur.gossip.proto.GossipMessage.class, dev.gmathur.gossip.proto.GossipMessage.Builder.class);
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * Unique ID to detect duplicates
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID to detect duplicates
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_NODE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceNodeId_ = "";
  /**
   * <pre>
   * Original sender
   * </pre>
   *
   * <code>string source_node_id = 2;</code>
   * @return The sourceNodeId.
   */
  @java.lang.Override
  public java.lang.String getSourceNodeId() {
    java.lang.Object ref = sourceNodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceNodeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Original sender
   * </pre>
   *
   * <code>string source_node_id = 2;</code>
   * @return The bytes for sourceNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceNodeIdBytes() {
    java.lang.Object ref = sourceNodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceNodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<dev.gmathur.gossip.proto.User> users_;
  /**
   * <pre>
   * User information being gossiped
   * </pre>
   *
   * <code>repeated .gossip.User users = 3;</code>
   */
  @java.lang.Override
  public java.util.List<dev.gmathur.gossip.proto.User> getUsersList() {
    return users_;
  }
  /**
   * <pre>
   * User information being gossiped
   * </pre>
   *
   * <code>repeated .gossip.User users = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.gmathur.gossip.proto.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <pre>
   * User information being gossiped
   * </pre>
   *
   * <code>repeated .gossip.User users = 3;</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <pre>
   * User information being gossiped
   * </pre>
   *
   * <code>repeated .gossip.User users = 3;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <pre>
   * User information being gossiped
   * </pre>
   *
   * <code>repeated .gossip.User users = 3;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  public static final int HOP_COUNT_FIELD_NUMBER = 4;
  private int hopCount_ = 0;
  /**
   * <pre>
   * Limits propagation
   * </pre>
   *
   * <code>int32 hop_count = 4;</code>
   * @return The hopCount.
   */
  @java.lang.Override
  public int getHopCount() {
    return hopCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceNodeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sourceNodeId_);
    }
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(3, users_.get(i));
    }
    if (hopCount_ != 0) {
      output.writeInt32(4, hopCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, messageId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sourceNodeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sourceNodeId_);
    }
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, users_.get(i));
    }
    if (hopCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, hopCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.gmathur.gossip.proto.GossipMessage)) {
      return super.equals(obj);
    }
    dev.gmathur.gossip.proto.GossipMessage other = (dev.gmathur.gossip.proto.GossipMessage) obj;

    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (!getSourceNodeId()
        .equals(other.getSourceNodeId())) return false;
    if (!getUsersList()
        .equals(other.getUsersList())) return false;
    if (getHopCount()
        != other.getHopCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + SOURCE_NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceNodeId().hashCode();
    if (getUsersCount() > 0) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsersList().hashCode();
    }
    hash = (37 * hash) + HOP_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getHopCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.gmathur.gossip.proto.GossipMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.gmathur.gossip.proto.GossipMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.GossipMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.gmathur.gossip.proto.GossipMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Gossip message containing multiple user updates
   * </pre>
   *
   * Protobuf type {@code gossip.GossipMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gossip.GossipMessage)
      dev.gmathur.gossip.proto.GossipMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_GossipMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_GossipMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.gmathur.gossip.proto.GossipMessage.class, dev.gmathur.gossip.proto.GossipMessage.Builder.class);
    }

    // Construct using dev.gmathur.gossip.proto.GossipMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = "";
      sourceNodeId_ = "";
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
      } else {
        users_ = null;
        usersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      hopCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_GossipMessage_descriptor;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.GossipMessage getDefaultInstanceForType() {
      return dev.gmathur.gossip.proto.GossipMessage.getDefaultInstance();
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.GossipMessage build() {
      dev.gmathur.gossip.proto.GossipMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.GossipMessage buildPartial() {
      dev.gmathur.gossip.proto.GossipMessage result = new dev.gmathur.gossip.proto.GossipMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(dev.gmathur.gossip.proto.GossipMessage result) {
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
    }

    private void buildPartial0(dev.gmathur.gossip.proto.GossipMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceNodeId_ = sourceNodeId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hopCount_ = hopCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.gmathur.gossip.proto.GossipMessage) {
        return mergeFrom((dev.gmathur.gossip.proto.GossipMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.gmathur.gossip.proto.GossipMessage other) {
      if (other == dev.gmathur.gossip.proto.GossipMessage.getDefaultInstance()) return this;
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSourceNodeId().isEmpty()) {
        sourceNodeId_ = other.sourceNodeId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000004);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      if (other.getHopCount() != 0) {
        setHopCount(other.getHopCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sourceNodeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dev.gmathur.gossip.proto.User m =
                  input.readMessage(
                      dev.gmathur.gossip.proto.User.parser(),
                      extensionRegistry);
              if (usersBuilder_ == null) {
                ensureUsersIsMutable();
                users_.add(m);
              } else {
                usersBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              hopCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * Unique ID to detect duplicates
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID to detect duplicates
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID to detect duplicates
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID to detect duplicates
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID to detect duplicates
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sourceNodeId_ = "";
    /**
     * <pre>
     * Original sender
     * </pre>
     *
     * <code>string source_node_id = 2;</code>
     * @return The sourceNodeId.
     */
    public java.lang.String getSourceNodeId() {
      java.lang.Object ref = sourceNodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceNodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Original sender
     * </pre>
     *
     * <code>string source_node_id = 2;</code>
     * @return The bytes for sourceNodeId.
     */
    public com.google.protobuf.ByteString
        getSourceNodeIdBytes() {
      java.lang.Object ref = sourceNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Original sender
     * </pre>
     *
     * <code>string source_node_id = 2;</code>
     * @param value The sourceNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNodeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceNodeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Original sender
     * </pre>
     *
     * <code>string source_node_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceNodeId() {
      sourceNodeId_ = getDefaultInstance().getSourceNodeId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Original sender
     * </pre>
     *
     * <code>string source_node_id = 2;</code>
     * @param value The bytes for sourceNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceNodeId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<dev.gmathur.gossip.proto.User> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        users_ = new java.util.ArrayList<dev.gmathur.gossip.proto.User>(users_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder> usersBuilder_;

    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.User> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public dev.gmathur.gossip.proto.User getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder setUsers(
        int index, dev.gmathur.gossip.proto.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder setUsers(
        int index, dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder addUsers(dev.gmathur.gossip.proto.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder addUsers(
        int index, dev.gmathur.gossip.proto.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder addUsers(
        dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder addUsers(
        int index, dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends dev.gmathur.gossip.proto.User> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder getUsersBuilder(
        int index) {
      return getUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public dev.gmathur.gossip.proto.UserOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public java.util.List<? extends dev.gmathur.gossip.proto.UserOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder addUsersBuilder() {
      return getUsersFieldBuilder().addBuilder(
          dev.gmathur.gossip.proto.User.getDefaultInstance());
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder addUsersBuilder(
        int index) {
      return getUsersFieldBuilder().addBuilder(
          index, dev.gmathur.gossip.proto.User.getDefaultInstance());
    }
    /**
     * <pre>
     * User information being gossiped
     * </pre>
     *
     * <code>repeated .gossip.User users = 3;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.User.Builder> 
         getUsersBuilderList() {
      return getUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder>(
                users_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }

    private int hopCount_ ;
    /**
     * <pre>
     * Limits propagation
     * </pre>
     *
     * <code>int32 hop_count = 4;</code>
     * @return The hopCount.
     */
    @java.lang.Override
    public int getHopCount() {
      return hopCount_;
    }
    /**
     * <pre>
     * Limits propagation
     * </pre>
     *
     * <code>int32 hop_count = 4;</code>
     * @param value The hopCount to set.
     * @return This builder for chaining.
     */
    public Builder setHopCount(int value) {

      hopCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Limits propagation
     * </pre>
     *
     * <code>int32 hop_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHopCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hopCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:gossip.GossipMessage)
  }

  // @@protoc_insertion_point(class_scope:gossip.GossipMessage)
  private static final dev.gmathur.gossip.proto.GossipMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.gmathur.gossip.proto.GossipMessage();
  }

  public static dev.gmathur.gossip.proto.GossipMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GossipMessage>
      PARSER = new com.google.protobuf.AbstractParser<GossipMessage>() {
    @java.lang.Override
    public GossipMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GossipMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GossipMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.gmathur.gossip.proto.GossipMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

