// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

public final class GossipProto {
  private GossipProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      GossipProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_User_VersionVectorEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_User_VersionVectorEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_GossipMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_GossipMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_SyncRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_SyncRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_SyncRequest_StateDigestEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_SyncRequest_StateDigestEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_StateVectorEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_StateVectorEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_StateVectorEntry_VersionVectorEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_StateVectorEntry_VersionVectorEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_SyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_SyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_JoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_JoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_JoinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_JoinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_NodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gossip_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gossip_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014gossip.proto\022\006gossip\"\261\001\n\004User\022\n\n\002id\030\001 " +
      "\001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\0227\n\016vers" +
      "ion_vector\030\004 \003(\0132\037.gossip.User.VersionVe" +
      "ctorEntry\022\021\n\ttimestamp\030\005 \001(\003\0324\n\022VersionV" +
      "ectorEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\004:\002" +
      "8\001\"k\n\rGossipMessage\022\022\n\nmessage_id\030\001 \001(\t\022" +
      "\026\n\016source_node_id\030\002 \001(\t\022\033\n\005users\030\003 \003(\0132\014" +
      ".gossip.User\022\021\n\thop_count\030\004 \001(\005\"\250\001\n\013Sync" +
      "Request\022\017\n\007node_id\030\001 \001(\t\022:\n\014state_digest" +
      "\030\002 \003(\0132$.gossip.SyncRequest.StateDigestE" +
      "ntry\032L\n\020StateDigestEntry\022\013\n\003key\030\001 \001(\t\022\'\n" +
      "\005value\030\002 \001(\0132\030.gossip.StateVectorEntry:\002" +
      "8\001\"\215\001\n\020StateVectorEntry\022C\n\016version_vecto" +
      "r\030\001 \003(\0132+.gossip.StateVectorEntry.Versio" +
      "nVectorEntry\0324\n\022VersionVectorEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\004:\0028\001\"3\n\014SyncRespon" +
      "se\022#\n\rmissing_users\030\001 \003(\0132\014.gossip.User\"" +
      "/\n\013JoinRequest\022\017\n\007node_id\030\001 \001(\t\022\017\n\007addre" +
      "ss\030\002 \001(\t\"5\n\014JoinResponse\022%\n\013known_nodes\030" +
      "\001 \003(\0132\020.gossip.NodeInfo\",\n\010NodeInfo\022\017\n\007n" +
      "ode_id\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\"\007\n\005Empty2\254" +
      "\001\n\rGossipService\0225\n\rReceiveGossip\022\025.goss" +
      "ip.GossipMessage\032\r.gossip.Empty\0221\n\004Sync\022" +
      "\023.gossip.SyncRequest\032\024.gossip.SyncRespon" +
      "se\0221\n\004Join\022\023.gossip.JoinRequest\032\024.gossip" +
      ".JoinResponseB)\n\030dev.gmathur.gossip.prot" +
      "oB\013GossipProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gossip_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gossip_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "VersionVector", "Timestamp", });
    internal_static_gossip_User_VersionVectorEntry_descriptor =
      internal_static_gossip_User_descriptor.getNestedTypes().get(0);
    internal_static_gossip_User_VersionVectorEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_User_VersionVectorEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_gossip_GossipMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gossip_GossipMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_GossipMessage_descriptor,
        new java.lang.String[] { "MessageId", "SourceNodeId", "Users", "HopCount", });
    internal_static_gossip_SyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gossip_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_SyncRequest_descriptor,
        new java.lang.String[] { "NodeId", "StateDigest", });
    internal_static_gossip_SyncRequest_StateDigestEntry_descriptor =
      internal_static_gossip_SyncRequest_descriptor.getNestedTypes().get(0);
    internal_static_gossip_SyncRequest_StateDigestEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_SyncRequest_StateDigestEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_gossip_StateVectorEntry_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gossip_StateVectorEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_StateVectorEntry_descriptor,
        new java.lang.String[] { "VersionVector", });
    internal_static_gossip_StateVectorEntry_VersionVectorEntry_descriptor =
      internal_static_gossip_StateVectorEntry_descriptor.getNestedTypes().get(0);
    internal_static_gossip_StateVectorEntry_VersionVectorEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_StateVectorEntry_VersionVectorEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_gossip_SyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gossip_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_SyncResponse_descriptor,
        new java.lang.String[] { "MissingUsers", });
    internal_static_gossip_JoinRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gossip_JoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_JoinRequest_descriptor,
        new java.lang.String[] { "NodeId", "Address", });
    internal_static_gossip_JoinResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_gossip_JoinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_JoinResponse_descriptor,
        new java.lang.String[] { "KnownNodes", });
    internal_static_gossip_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_gossip_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_NodeInfo_descriptor,
        new java.lang.String[] { "NodeId", "Address", });
    internal_static_gossip_Empty_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_gossip_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gossip_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
