// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

/**
 * Protobuf type {@code gossip.JoinResponse}
 */
public final class JoinResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gossip.JoinResponse)
    JoinResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      JoinResponse.class.getName());
  }
  // Use JoinResponse.newBuilder() to construct.
  private JoinResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JoinResponse() {
    knownNodes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_JoinResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_JoinResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.gmathur.gossip.proto.JoinResponse.class, dev.gmathur.gossip.proto.JoinResponse.Builder.class);
  }

  public static final int KNOWN_NODES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<dev.gmathur.gossip.proto.NodeInfo> knownNodes_;
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.gmathur.gossip.proto.NodeInfo> getKnownNodesList() {
    return knownNodes_;
  }
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.gmathur.gossip.proto.NodeInfoOrBuilder> 
      getKnownNodesOrBuilderList() {
    return knownNodes_;
  }
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  @java.lang.Override
  public int getKnownNodesCount() {
    return knownNodes_.size();
  }
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.NodeInfo getKnownNodes(int index) {
    return knownNodes_.get(index);
  }
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.NodeInfoOrBuilder getKnownNodesOrBuilder(
      int index) {
    return knownNodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < knownNodes_.size(); i++) {
      output.writeMessage(1, knownNodes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < knownNodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, knownNodes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.gmathur.gossip.proto.JoinResponse)) {
      return super.equals(obj);
    }
    dev.gmathur.gossip.proto.JoinResponse other = (dev.gmathur.gossip.proto.JoinResponse) obj;

    if (!getKnownNodesList()
        .equals(other.getKnownNodesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKnownNodesCount() > 0) {
      hash = (37 * hash) + KNOWN_NODES_FIELD_NUMBER;
      hash = (53 * hash) + getKnownNodesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.gmathur.gossip.proto.JoinResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.gmathur.gossip.proto.JoinResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.JoinResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.gmathur.gossip.proto.JoinResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gossip.JoinResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gossip.JoinResponse)
      dev.gmathur.gossip.proto.JoinResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_JoinResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_JoinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.gmathur.gossip.proto.JoinResponse.class, dev.gmathur.gossip.proto.JoinResponse.Builder.class);
    }

    // Construct using dev.gmathur.gossip.proto.JoinResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (knownNodesBuilder_ == null) {
        knownNodes_ = java.util.Collections.emptyList();
      } else {
        knownNodes_ = null;
        knownNodesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_JoinResponse_descriptor;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.JoinResponse getDefaultInstanceForType() {
      return dev.gmathur.gossip.proto.JoinResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.JoinResponse build() {
      dev.gmathur.gossip.proto.JoinResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.JoinResponse buildPartial() {
      dev.gmathur.gossip.proto.JoinResponse result = new dev.gmathur.gossip.proto.JoinResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(dev.gmathur.gossip.proto.JoinResponse result) {
      if (knownNodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          knownNodes_ = java.util.Collections.unmodifiableList(knownNodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.knownNodes_ = knownNodes_;
      } else {
        result.knownNodes_ = knownNodesBuilder_.build();
      }
    }

    private void buildPartial0(dev.gmathur.gossip.proto.JoinResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.gmathur.gossip.proto.JoinResponse) {
        return mergeFrom((dev.gmathur.gossip.proto.JoinResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.gmathur.gossip.proto.JoinResponse other) {
      if (other == dev.gmathur.gossip.proto.JoinResponse.getDefaultInstance()) return this;
      if (knownNodesBuilder_ == null) {
        if (!other.knownNodes_.isEmpty()) {
          if (knownNodes_.isEmpty()) {
            knownNodes_ = other.knownNodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureKnownNodesIsMutable();
            knownNodes_.addAll(other.knownNodes_);
          }
          onChanged();
        }
      } else {
        if (!other.knownNodes_.isEmpty()) {
          if (knownNodesBuilder_.isEmpty()) {
            knownNodesBuilder_.dispose();
            knownNodesBuilder_ = null;
            knownNodes_ = other.knownNodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            knownNodesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getKnownNodesFieldBuilder() : null;
          } else {
            knownNodesBuilder_.addAllMessages(other.knownNodes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dev.gmathur.gossip.proto.NodeInfo m =
                  input.readMessage(
                      dev.gmathur.gossip.proto.NodeInfo.parser(),
                      extensionRegistry);
              if (knownNodesBuilder_ == null) {
                ensureKnownNodesIsMutable();
                knownNodes_.add(m);
              } else {
                knownNodesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<dev.gmathur.gossip.proto.NodeInfo> knownNodes_ =
      java.util.Collections.emptyList();
    private void ensureKnownNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        knownNodes_ = new java.util.ArrayList<dev.gmathur.gossip.proto.NodeInfo>(knownNodes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.NodeInfo, dev.gmathur.gossip.proto.NodeInfo.Builder, dev.gmathur.gossip.proto.NodeInfoOrBuilder> knownNodesBuilder_;

    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.NodeInfo> getKnownNodesList() {
      if (knownNodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(knownNodes_);
      } else {
        return knownNodesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public int getKnownNodesCount() {
      if (knownNodesBuilder_ == null) {
        return knownNodes_.size();
      } else {
        return knownNodesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public dev.gmathur.gossip.proto.NodeInfo getKnownNodes(int index) {
      if (knownNodesBuilder_ == null) {
        return knownNodes_.get(index);
      } else {
        return knownNodesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder setKnownNodes(
        int index, dev.gmathur.gossip.proto.NodeInfo value) {
      if (knownNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKnownNodesIsMutable();
        knownNodes_.set(index, value);
        onChanged();
      } else {
        knownNodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder setKnownNodes(
        int index, dev.gmathur.gossip.proto.NodeInfo.Builder builderForValue) {
      if (knownNodesBuilder_ == null) {
        ensureKnownNodesIsMutable();
        knownNodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        knownNodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder addKnownNodes(dev.gmathur.gossip.proto.NodeInfo value) {
      if (knownNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKnownNodesIsMutable();
        knownNodes_.add(value);
        onChanged();
      } else {
        knownNodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder addKnownNodes(
        int index, dev.gmathur.gossip.proto.NodeInfo value) {
      if (knownNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureKnownNodesIsMutable();
        knownNodes_.add(index, value);
        onChanged();
      } else {
        knownNodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder addKnownNodes(
        dev.gmathur.gossip.proto.NodeInfo.Builder builderForValue) {
      if (knownNodesBuilder_ == null) {
        ensureKnownNodesIsMutable();
        knownNodes_.add(builderForValue.build());
        onChanged();
      } else {
        knownNodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder addKnownNodes(
        int index, dev.gmathur.gossip.proto.NodeInfo.Builder builderForValue) {
      if (knownNodesBuilder_ == null) {
        ensureKnownNodesIsMutable();
        knownNodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        knownNodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder addAllKnownNodes(
        java.lang.Iterable<? extends dev.gmathur.gossip.proto.NodeInfo> values) {
      if (knownNodesBuilder_ == null) {
        ensureKnownNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, knownNodes_);
        onChanged();
      } else {
        knownNodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder clearKnownNodes() {
      if (knownNodesBuilder_ == null) {
        knownNodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        knownNodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public Builder removeKnownNodes(int index) {
      if (knownNodesBuilder_ == null) {
        ensureKnownNodesIsMutable();
        knownNodes_.remove(index);
        onChanged();
      } else {
        knownNodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public dev.gmathur.gossip.proto.NodeInfo.Builder getKnownNodesBuilder(
        int index) {
      return getKnownNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public dev.gmathur.gossip.proto.NodeInfoOrBuilder getKnownNodesOrBuilder(
        int index) {
      if (knownNodesBuilder_ == null) {
        return knownNodes_.get(index);  } else {
        return knownNodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public java.util.List<? extends dev.gmathur.gossip.proto.NodeInfoOrBuilder> 
         getKnownNodesOrBuilderList() {
      if (knownNodesBuilder_ != null) {
        return knownNodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(knownNodes_);
      }
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public dev.gmathur.gossip.proto.NodeInfo.Builder addKnownNodesBuilder() {
      return getKnownNodesFieldBuilder().addBuilder(
          dev.gmathur.gossip.proto.NodeInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public dev.gmathur.gossip.proto.NodeInfo.Builder addKnownNodesBuilder(
        int index) {
      return getKnownNodesFieldBuilder().addBuilder(
          index, dev.gmathur.gossip.proto.NodeInfo.getDefaultInstance());
    }
    /**
     * <pre>
     * Information about other nodes
     * </pre>
     *
     * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.NodeInfo.Builder> 
         getKnownNodesBuilderList() {
      return getKnownNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.NodeInfo, dev.gmathur.gossip.proto.NodeInfo.Builder, dev.gmathur.gossip.proto.NodeInfoOrBuilder> 
        getKnownNodesFieldBuilder() {
      if (knownNodesBuilder_ == null) {
        knownNodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            dev.gmathur.gossip.proto.NodeInfo, dev.gmathur.gossip.proto.NodeInfo.Builder, dev.gmathur.gossip.proto.NodeInfoOrBuilder>(
                knownNodes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        knownNodes_ = null;
      }
      return knownNodesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:gossip.JoinResponse)
  }

  // @@protoc_insertion_point(class_scope:gossip.JoinResponse)
  private static final dev.gmathur.gossip.proto.JoinResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.gmathur.gossip.proto.JoinResponse();
  }

  public static dev.gmathur.gossip.proto.JoinResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinResponse>
      PARSER = new com.google.protobuf.AbstractParser<JoinResponse>() {
    @java.lang.Override
    public JoinResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JoinResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.gmathur.gossip.proto.JoinResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

