// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

public interface JoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gossip.JoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  java.util.List<dev.gmathur.gossip.proto.NodeInfo> 
      getKnownNodesList();
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  dev.gmathur.gossip.proto.NodeInfo getKnownNodes(int index);
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  int getKnownNodesCount();
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  java.util.List<? extends dev.gmathur.gossip.proto.NodeInfoOrBuilder> 
      getKnownNodesOrBuilderList();
  /**
   * <pre>
   * Information about other nodes
   * </pre>
   *
   * <code>repeated .gossip.NodeInfo known_nodes = 1;</code>
   */
  dev.gmathur.gossip.proto.NodeInfoOrBuilder getKnownNodesOrBuilder(
      int index);
}
