// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

public interface StateVectorEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gossip.StateVectorEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  int getVersionVectorCount();
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  boolean containsVersionVector(
      java.lang.String key);
  /**
   * Use {@link #getVersionVectorMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getVersionVector();
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getVersionVectorMap();
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  long getVersionVectorOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  long getVersionVectorOrThrow(
      java.lang.String key);
}
