// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

/**
 * Protobuf type {@code gossip.StateVectorEntry}
 */
public final class StateVectorEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gossip.StateVectorEntry)
    StateVectorEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      StateVectorEntry.class.getName());
  }
  // Use StateVectorEntry.newBuilder() to construct.
  private StateVectorEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StateVectorEntry() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetVersionVector();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.gmathur.gossip.proto.StateVectorEntry.class, dev.gmathur.gossip.proto.StateVectorEntry.Builder.class);
  }

  public static final int VERSION_VECTOR_FIELD_NUMBER = 1;
  private static final class VersionVectorDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_VersionVectorEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT64,
                0L);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> versionVector_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetVersionVector() {
    if (versionVector_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          VersionVectorDefaultEntryHolder.defaultEntry);
    }
    return versionVector_;
  }
  public int getVersionVectorCount() {
    return internalGetVersionVector().getMap().size();
  }
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  @java.lang.Override
  public boolean containsVersionVector(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetVersionVector().getMap().containsKey(key);
  }
  /**
   * Use {@link #getVersionVectorMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getVersionVector() {
    return getVersionVectorMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Long> getVersionVectorMap() {
    return internalGetVersionVector().getMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  @java.lang.Override
  public long getVersionVectorOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetVersionVector().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
   */
  @java.lang.Override
  public long getVersionVectorOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetVersionVector().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetVersionVector(),
        VersionVectorDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetVersionVector().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      versionVector__ = VersionVectorDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, versionVector__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.gmathur.gossip.proto.StateVectorEntry)) {
      return super.equals(obj);
    }
    dev.gmathur.gossip.proto.StateVectorEntry other = (dev.gmathur.gossip.proto.StateVectorEntry) obj;

    if (!internalGetVersionVector().equals(
        other.internalGetVersionVector())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetVersionVector().getMap().isEmpty()) {
      hash = (37 * hash) + VERSION_VECTOR_FIELD_NUMBER;
      hash = (53 * hash) + internalGetVersionVector().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.gmathur.gossip.proto.StateVectorEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.gmathur.gossip.proto.StateVectorEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.StateVectorEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.gmathur.gossip.proto.StateVectorEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gossip.StateVectorEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gossip.StateVectorEntry)
      dev.gmathur.gossip.proto.StateVectorEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetVersionVector();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableVersionVector();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.gmathur.gossip.proto.StateVectorEntry.class, dev.gmathur.gossip.proto.StateVectorEntry.Builder.class);
    }

    // Construct using dev.gmathur.gossip.proto.StateVectorEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableVersionVector().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_StateVectorEntry_descriptor;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.StateVectorEntry getDefaultInstanceForType() {
      return dev.gmathur.gossip.proto.StateVectorEntry.getDefaultInstance();
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.StateVectorEntry build() {
      dev.gmathur.gossip.proto.StateVectorEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.StateVectorEntry buildPartial() {
      dev.gmathur.gossip.proto.StateVectorEntry result = new dev.gmathur.gossip.proto.StateVectorEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.gmathur.gossip.proto.StateVectorEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.versionVector_ = internalGetVersionVector();
        result.versionVector_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.gmathur.gossip.proto.StateVectorEntry) {
        return mergeFrom((dev.gmathur.gossip.proto.StateVectorEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.gmathur.gossip.proto.StateVectorEntry other) {
      if (other == dev.gmathur.gossip.proto.StateVectorEntry.getDefaultInstance()) return this;
      internalGetMutableVersionVector().mergeFrom(
          other.internalGetVersionVector());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              versionVector__ = input.readMessage(
                  VersionVectorDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableVersionVector().getMutableMap().put(
                  versionVector__.getKey(), versionVector__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> versionVector_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetVersionVector() {
      if (versionVector_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            VersionVectorDefaultEntryHolder.defaultEntry);
      }
      return versionVector_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
        internalGetMutableVersionVector() {
      if (versionVector_ == null) {
        versionVector_ = com.google.protobuf.MapField.newMapField(
            VersionVectorDefaultEntryHolder.defaultEntry);
      }
      if (!versionVector_.isMutable()) {
        versionVector_ = versionVector_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return versionVector_;
    }
    public int getVersionVectorCount() {
      return internalGetVersionVector().getMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    @java.lang.Override
    public boolean containsVersionVector(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetVersionVector().getMap().containsKey(key);
    }
    /**
     * Use {@link #getVersionVectorMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getVersionVector() {
      return getVersionVectorMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getVersionVectorMap() {
      return internalGetVersionVector().getMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    @java.lang.Override
    public long getVersionVectorOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetVersionVector().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    @java.lang.Override
    public long getVersionVectorOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetVersionVector().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearVersionVector() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableVersionVector().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    public Builder removeVersionVector(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableVersionVector().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
        getMutableVersionVector() {
      bitField0_ |= 0x00000001;
      return internalGetMutableVersionVector().getMutableMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    public Builder putVersionVector(
        java.lang.String key,
        long value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableVersionVector().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; version_vector = 1;</code>
     */
    public Builder putAllVersionVector(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableVersionVector().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:gossip.StateVectorEntry)
  }

  // @@protoc_insertion_point(class_scope:gossip.StateVectorEntry)
  private static final dev.gmathur.gossip.proto.StateVectorEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.gmathur.gossip.proto.StateVectorEntry();
  }

  public static dev.gmathur.gossip.proto.StateVectorEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StateVectorEntry>
      PARSER = new com.google.protobuf.AbstractParser<StateVectorEntry>() {
    @java.lang.Override
    public StateVectorEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StateVectorEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StateVectorEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.gmathur.gossip.proto.StateVectorEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

