// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

public interface SyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gossip.SyncRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  int getStateDigestCount();
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  boolean containsStateDigest(
      java.lang.String key);
  /**
   * Use {@link #getStateDigestMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
  getStateDigest();
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
  getStateDigestMap();
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrDefault(
      java.lang.String key,
      /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry defaultValue);
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrThrow(
      java.lang.String key);
}
