// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

/**
 * <pre>
 * Sync request for anti-entropy
 * </pre>
 *
 * Protobuf type {@code gossip.SyncRequest}
 */
public final class SyncRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gossip.SyncRequest)
    SyncRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SyncRequest.class.getName());
  }
  // Use SyncRequest.newBuilder() to construct.
  private SyncRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SyncRequest() {
    nodeId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetStateDigest();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.gmathur.gossip.proto.SyncRequest.class, dev.gmathur.gossip.proto.SyncRequest.Builder.class);
  }

  public static final int NODE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nodeId_ = "";
  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    java.lang.Object ref = nodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_DIGEST_FIELD_NUMBER = 2;
  private static final class StateDigestDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>newDefaultInstance(
                dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_StateDigestEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                dev.gmathur.gossip.proto.StateVectorEntry.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> stateDigest_;
  private com.google.protobuf.MapField<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
  internalGetStateDigest() {
    if (stateDigest_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StateDigestDefaultEntryHolder.defaultEntry);
    }
    return stateDigest_;
  }
  public int getStateDigestCount() {
    return internalGetStateDigest().getMap().size();
  }
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  @java.lang.Override
  public boolean containsStateDigest(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStateDigest().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStateDigestMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> getStateDigest() {
    return getStateDigestMap();
  }
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> getStateDigestMap() {
    return internalGetStateDigest().getMap();
  }
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  @java.lang.Override
  public /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrDefault(
      java.lang.String key,
      /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> map =
        internalGetStateDigest().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Digest of the sender's state (user IDs and their version vector)
   * </pre>
   *
   * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> map =
        internalGetStateDigest().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, nodeId_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetStateDigest(),
        StateDigestDefaultEntryHolder.defaultEntry,
        2);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nodeId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nodeId_);
    }
    for (java.util.Map.Entry<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> entry
         : internalGetStateDigest().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
      stateDigest__ = StateDigestDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, stateDigest__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.gmathur.gossip.proto.SyncRequest)) {
      return super.equals(obj);
    }
    dev.gmathur.gossip.proto.SyncRequest other = (dev.gmathur.gossip.proto.SyncRequest) obj;

    if (!getNodeId()
        .equals(other.getNodeId())) return false;
    if (!internalGetStateDigest().equals(
        other.internalGetStateDigest())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId().hashCode();
    if (!internalGetStateDigest().getMap().isEmpty()) {
      hash = (37 * hash) + STATE_DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStateDigest().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.gmathur.gossip.proto.SyncRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.gmathur.gossip.proto.SyncRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.SyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.gmathur.gossip.proto.SyncRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Sync request for anti-entropy
   * </pre>
   *
   * Protobuf type {@code gossip.SyncRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gossip.SyncRequest)
      dev.gmathur.gossip.proto.SyncRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetStateDigest();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableStateDigest();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.gmathur.gossip.proto.SyncRequest.class, dev.gmathur.gossip.proto.SyncRequest.Builder.class);
    }

    // Construct using dev.gmathur.gossip.proto.SyncRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nodeId_ = "";
      internalGetMutableStateDigest().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncRequest_descriptor;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncRequest getDefaultInstanceForType() {
      return dev.gmathur.gossip.proto.SyncRequest.getDefaultInstance();
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncRequest build() {
      dev.gmathur.gossip.proto.SyncRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncRequest buildPartial() {
      dev.gmathur.gossip.proto.SyncRequest result = new dev.gmathur.gossip.proto.SyncRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.gmathur.gossip.proto.SyncRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nodeId_ = nodeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stateDigest_ = internalGetStateDigest().build(StateDigestDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.gmathur.gossip.proto.SyncRequest) {
        return mergeFrom((dev.gmathur.gossip.proto.SyncRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.gmathur.gossip.proto.SyncRequest other) {
      if (other == dev.gmathur.gossip.proto.SyncRequest.getDefaultInstance()) return this;
      if (!other.getNodeId().isEmpty()) {
        nodeId_ = other.nodeId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableStateDigest().mergeFrom(
          other.internalGetStateDigest());
      bitField0_ |= 0x00000002;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              nodeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
              stateDigest__ = input.readMessage(
                  StateDigestDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStateDigest().ensureBuilderMap().put(
                  stateDigest__.getKey(), stateDigest__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object nodeId_ = "";
    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nodeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      nodeId_ = getDefaultInstance().getNodeId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nodeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private static final class StateDigestConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder, dev.gmathur.gossip.proto.StateVectorEntry> {
      @java.lang.Override
      public dev.gmathur.gossip.proto.StateVectorEntry build(dev.gmathur.gossip.proto.StateVectorEntryOrBuilder val) {
        if (val instanceof dev.gmathur.gossip.proto.StateVectorEntry) { return (dev.gmathur.gossip.proto.StateVectorEntry) val; }
        return ((dev.gmathur.gossip.proto.StateVectorEntry.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> defaultEntry() {
        return StateDigestDefaultEntryHolder.defaultEntry;
      }
    };
    private static final StateDigestConverter stateDigestConverter = new StateDigestConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder, dev.gmathur.gossip.proto.StateVectorEntry, dev.gmathur.gossip.proto.StateVectorEntry.Builder> stateDigest_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder, dev.gmathur.gossip.proto.StateVectorEntry, dev.gmathur.gossip.proto.StateVectorEntry.Builder>
        internalGetStateDigest() {
      if (stateDigest_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(stateDigestConverter);
      }
      return stateDigest_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder, dev.gmathur.gossip.proto.StateVectorEntry, dev.gmathur.gossip.proto.StateVectorEntry.Builder>
        internalGetMutableStateDigest() {
      if (stateDigest_ == null) {
        stateDigest_ = new com.google.protobuf.MapFieldBuilder<>(stateDigestConverter);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return stateDigest_;
    }
    public int getStateDigestCount() {
      return internalGetStateDigest().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    @java.lang.Override
    public boolean containsStateDigest(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStateDigest().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getStateDigestMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> getStateDigest() {
      return getStateDigestMap();
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> getStateDigestMap() {
      return internalGetStateDigest().getImmutableMap();
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrDefault(
        java.lang.String key,
        /* nullable */
dev.gmathur.gossip.proto.StateVectorEntry defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder> map = internalGetMutableStateDigest().ensureBuilderMap();
      return map.containsKey(key) ? stateDigestConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    @java.lang.Override
    public dev.gmathur.gossip.proto.StateVectorEntry getStateDigestOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder> map = internalGetMutableStateDigest().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return stateDigestConverter.build(map.get(key));
    }
    public Builder clearStateDigest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableStateDigest().clear();
      return this;
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    public Builder removeStateDigest(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStateDigest().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry>
        getMutableStateDigest() {
      bitField0_ |= 0x00000002;
      return internalGetMutableStateDigest().ensureMessageMap();
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    public Builder putStateDigest(
        java.lang.String key,
        dev.gmathur.gossip.proto.StateVectorEntry value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableStateDigest().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    public Builder putAllStateDigest(
        java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> values) {
      for (java.util.Map.Entry<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntry> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableStateDigest().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * Digest of the sender's state (user IDs and their version vector)
     * </pre>
     *
     * <code>map&lt;string, .gossip.StateVectorEntry&gt; state_digest = 2;</code>
     */
    public dev.gmathur.gossip.proto.StateVectorEntry.Builder putStateDigestBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, dev.gmathur.gossip.proto.StateVectorEntryOrBuilder> builderMap = internalGetMutableStateDigest().ensureBuilderMap();
      dev.gmathur.gossip.proto.StateVectorEntryOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = dev.gmathur.gossip.proto.StateVectorEntry.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof dev.gmathur.gossip.proto.StateVectorEntry) {
        entry = ((dev.gmathur.gossip.proto.StateVectorEntry) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (dev.gmathur.gossip.proto.StateVectorEntry.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:gossip.SyncRequest)
  }

  // @@protoc_insertion_point(class_scope:gossip.SyncRequest)
  private static final dev.gmathur.gossip.proto.SyncRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.gmathur.gossip.proto.SyncRequest();
  }

  public static dev.gmathur.gossip.proto.SyncRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncRequest>
      PARSER = new com.google.protobuf.AbstractParser<SyncRequest>() {
    @java.lang.Override
    public SyncRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SyncRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.gmathur.gossip.proto.SyncRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

