// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

public interface SyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gossip.SyncResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  java.util.List<dev.gmathur.gossip.proto.User> 
      getMissingUsersList();
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  dev.gmathur.gossip.proto.User getMissingUsers(int index);
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  int getMissingUsersCount();
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  java.util.List<? extends dev.gmathur.gossip.proto.UserOrBuilder> 
      getMissingUsersOrBuilderList();
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  dev.gmathur.gossip.proto.UserOrBuilder getMissingUsersOrBuilder(
      int index);
}
