// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gossip.proto
// Protobuf Java Version: 4.29.3

package dev.gmathur.gossip.proto;

/**
 * <pre>
 * Response to a sync request
 * </pre>
 *
 * Protobuf type {@code gossip.SyncResponse}
 */
public final class SyncResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:gossip.SyncResponse)
    SyncResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SyncResponse.class.getName());
  }
  // Use SyncResponse.newBuilder() to construct.
  private SyncResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SyncResponse() {
    missingUsers_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.gmathur.gossip.proto.SyncResponse.class, dev.gmathur.gossip.proto.SyncResponse.Builder.class);
  }

  public static final int MISSING_USERS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<dev.gmathur.gossip.proto.User> missingUsers_;
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<dev.gmathur.gossip.proto.User> getMissingUsersList() {
    return missingUsers_;
  }
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.gmathur.gossip.proto.UserOrBuilder> 
      getMissingUsersOrBuilderList() {
    return missingUsers_;
  }
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  @java.lang.Override
  public int getMissingUsersCount() {
    return missingUsers_.size();
  }
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.User getMissingUsers(int index) {
    return missingUsers_.get(index);
  }
  /**
   * <pre>
   * Users the requester is missing
   * </pre>
   *
   * <code>repeated .gossip.User missing_users = 1;</code>
   */
  @java.lang.Override
  public dev.gmathur.gossip.proto.UserOrBuilder getMissingUsersOrBuilder(
      int index) {
    return missingUsers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < missingUsers_.size(); i++) {
      output.writeMessage(1, missingUsers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < missingUsers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, missingUsers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.gmathur.gossip.proto.SyncResponse)) {
      return super.equals(obj);
    }
    dev.gmathur.gossip.proto.SyncResponse other = (dev.gmathur.gossip.proto.SyncResponse) obj;

    if (!getMissingUsersList()
        .equals(other.getMissingUsersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMissingUsersCount() > 0) {
      hash = (37 * hash) + MISSING_USERS_FIELD_NUMBER;
      hash = (53 * hash) + getMissingUsersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.gmathur.gossip.proto.SyncResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.gmathur.gossip.proto.SyncResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.gmathur.gossip.proto.SyncResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.gmathur.gossip.proto.SyncResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response to a sync request
   * </pre>
   *
   * Protobuf type {@code gossip.SyncResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gossip.SyncResponse)
      dev.gmathur.gossip.proto.SyncResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.gmathur.gossip.proto.SyncResponse.class, dev.gmathur.gossip.proto.SyncResponse.Builder.class);
    }

    // Construct using dev.gmathur.gossip.proto.SyncResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (missingUsersBuilder_ == null) {
        missingUsers_ = java.util.Collections.emptyList();
      } else {
        missingUsers_ = null;
        missingUsersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.gmathur.gossip.proto.GossipProto.internal_static_gossip_SyncResponse_descriptor;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncResponse getDefaultInstanceForType() {
      return dev.gmathur.gossip.proto.SyncResponse.getDefaultInstance();
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncResponse build() {
      dev.gmathur.gossip.proto.SyncResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.gmathur.gossip.proto.SyncResponse buildPartial() {
      dev.gmathur.gossip.proto.SyncResponse result = new dev.gmathur.gossip.proto.SyncResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(dev.gmathur.gossip.proto.SyncResponse result) {
      if (missingUsersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          missingUsers_ = java.util.Collections.unmodifiableList(missingUsers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.missingUsers_ = missingUsers_;
      } else {
        result.missingUsers_ = missingUsersBuilder_.build();
      }
    }

    private void buildPartial0(dev.gmathur.gossip.proto.SyncResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.gmathur.gossip.proto.SyncResponse) {
        return mergeFrom((dev.gmathur.gossip.proto.SyncResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.gmathur.gossip.proto.SyncResponse other) {
      if (other == dev.gmathur.gossip.proto.SyncResponse.getDefaultInstance()) return this;
      if (missingUsersBuilder_ == null) {
        if (!other.missingUsers_.isEmpty()) {
          if (missingUsers_.isEmpty()) {
            missingUsers_ = other.missingUsers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMissingUsersIsMutable();
            missingUsers_.addAll(other.missingUsers_);
          }
          onChanged();
        }
      } else {
        if (!other.missingUsers_.isEmpty()) {
          if (missingUsersBuilder_.isEmpty()) {
            missingUsersBuilder_.dispose();
            missingUsersBuilder_ = null;
            missingUsers_ = other.missingUsers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            missingUsersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMissingUsersFieldBuilder() : null;
          } else {
            missingUsersBuilder_.addAllMessages(other.missingUsers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dev.gmathur.gossip.proto.User m =
                  input.readMessage(
                      dev.gmathur.gossip.proto.User.parser(),
                      extensionRegistry);
              if (missingUsersBuilder_ == null) {
                ensureMissingUsersIsMutable();
                missingUsers_.add(m);
              } else {
                missingUsersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<dev.gmathur.gossip.proto.User> missingUsers_ =
      java.util.Collections.emptyList();
    private void ensureMissingUsersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        missingUsers_ = new java.util.ArrayList<dev.gmathur.gossip.proto.User>(missingUsers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder> missingUsersBuilder_;

    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.User> getMissingUsersList() {
      if (missingUsersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(missingUsers_);
      } else {
        return missingUsersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public int getMissingUsersCount() {
      if (missingUsersBuilder_ == null) {
        return missingUsers_.size();
      } else {
        return missingUsersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public dev.gmathur.gossip.proto.User getMissingUsers(int index) {
      if (missingUsersBuilder_ == null) {
        return missingUsers_.get(index);
      } else {
        return missingUsersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder setMissingUsers(
        int index, dev.gmathur.gossip.proto.User value) {
      if (missingUsersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMissingUsersIsMutable();
        missingUsers_.set(index, value);
        onChanged();
      } else {
        missingUsersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder setMissingUsers(
        int index, dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (missingUsersBuilder_ == null) {
        ensureMissingUsersIsMutable();
        missingUsers_.set(index, builderForValue.build());
        onChanged();
      } else {
        missingUsersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder addMissingUsers(dev.gmathur.gossip.proto.User value) {
      if (missingUsersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMissingUsersIsMutable();
        missingUsers_.add(value);
        onChanged();
      } else {
        missingUsersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder addMissingUsers(
        int index, dev.gmathur.gossip.proto.User value) {
      if (missingUsersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMissingUsersIsMutable();
        missingUsers_.add(index, value);
        onChanged();
      } else {
        missingUsersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder addMissingUsers(
        dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (missingUsersBuilder_ == null) {
        ensureMissingUsersIsMutable();
        missingUsers_.add(builderForValue.build());
        onChanged();
      } else {
        missingUsersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder addMissingUsers(
        int index, dev.gmathur.gossip.proto.User.Builder builderForValue) {
      if (missingUsersBuilder_ == null) {
        ensureMissingUsersIsMutable();
        missingUsers_.add(index, builderForValue.build());
        onChanged();
      } else {
        missingUsersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder addAllMissingUsers(
        java.lang.Iterable<? extends dev.gmathur.gossip.proto.User> values) {
      if (missingUsersBuilder_ == null) {
        ensureMissingUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, missingUsers_);
        onChanged();
      } else {
        missingUsersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder clearMissingUsers() {
      if (missingUsersBuilder_ == null) {
        missingUsers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        missingUsersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public Builder removeMissingUsers(int index) {
      if (missingUsersBuilder_ == null) {
        ensureMissingUsersIsMutable();
        missingUsers_.remove(index);
        onChanged();
      } else {
        missingUsersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder getMissingUsersBuilder(
        int index) {
      return getMissingUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public dev.gmathur.gossip.proto.UserOrBuilder getMissingUsersOrBuilder(
        int index) {
      if (missingUsersBuilder_ == null) {
        return missingUsers_.get(index);  } else {
        return missingUsersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public java.util.List<? extends dev.gmathur.gossip.proto.UserOrBuilder> 
         getMissingUsersOrBuilderList() {
      if (missingUsersBuilder_ != null) {
        return missingUsersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(missingUsers_);
      }
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder addMissingUsersBuilder() {
      return getMissingUsersFieldBuilder().addBuilder(
          dev.gmathur.gossip.proto.User.getDefaultInstance());
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public dev.gmathur.gossip.proto.User.Builder addMissingUsersBuilder(
        int index) {
      return getMissingUsersFieldBuilder().addBuilder(
          index, dev.gmathur.gossip.proto.User.getDefaultInstance());
    }
    /**
     * <pre>
     * Users the requester is missing
     * </pre>
     *
     * <code>repeated .gossip.User missing_users = 1;</code>
     */
    public java.util.List<dev.gmathur.gossip.proto.User.Builder> 
         getMissingUsersBuilderList() {
      return getMissingUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder> 
        getMissingUsersFieldBuilder() {
      if (missingUsersBuilder_ == null) {
        missingUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            dev.gmathur.gossip.proto.User, dev.gmathur.gossip.proto.User.Builder, dev.gmathur.gossip.proto.UserOrBuilder>(
                missingUsers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        missingUsers_ = null;
      }
      return missingUsersBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:gossip.SyncResponse)
  }

  // @@protoc_insertion_point(class_scope:gossip.SyncResponse)
  private static final dev.gmathur.gossip.proto.SyncResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.gmathur.gossip.proto.SyncResponse();
  }

  public static dev.gmathur.gossip.proto.SyncResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SyncResponse>
      PARSER = new com.google.protobuf.AbstractParser<SyncResponse>() {
    @java.lang.Override
    public SyncResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SyncResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.gmathur.gossip.proto.SyncResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

