version: '3'
services:
  app:
    container_name: file-analyzer
    image: file-analyzer:latest
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
        - './src/main/resources/input/:/home/app/input'
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis-server
    ports:
      - "6379:6379"
